replicaCount: #{VAR_ENV_HELM_VALUES_DEPLOY_REPLICACOUNT}#
revisionHistoryLimit: #{VAR_ENV_HELM_VALUES_DEPLOY_REVISION_HISTORY_LIMIT}#

image:
  repository: #{VAR_ENV_HELM_VALUES_DEPLOY_IMAGE_REPOSITORY}#
  tag: #{VAR_ENV_HELM_VALUES_DEPLOY_IMAGE_TAG}#
  pullPolicy: #{VAR_ENV_HELM_VALUES_DEPLOY_IMAGE_PULL_POLICY}#

container:
  name: #{VAR_ENV_HELM_VALUES_DEPLOY_CONTAINER_NAME}#
  port: #{VAR_ENV_HELM_VALUES_DEPLOY_CONTAINER_PORT}#

resources:
  requests:
    cpu: #{VAR_ENV_HELM_VALUES_DEPLOY_RSCS_REQUESTS_CPU}#
    memory: #{VAR_ENV_HELM_VALUES_DEPLOY_RSCS_REQUESTS_MEMORY}#
  limits:
    cpu: #{VAR_ENV_HELM_VALUES_DEPLOY_RSCS_LIMITS_CPU}#
    memory: #{VAR_ENV_HELM_VALUES_DEPLOY_RSCS_LIMITS_MEMORY}#

service:
  type: #{VAR_ENV_HELM_VALUES_SVC_TYPE}#
  port: #{VAR_ENV_HELM_VALUES_SVC_PORT}#
  targetPort: #{VAR_ENV_HELM_VALUES_SVC_TARGET_PORT}#


ingress:
  enabled: #{VAR_ENV_HELM_VALUES_INGRESS_ENABLED}#
  className: #{VAR_ENV_HELM_VALUES_INGRESS_CLASSNAME}#
  host: #{VAR_ENV_HELM_VALUES_INGRESS_HOST}#
  path: #{VAR_ENV_HELM_VALUES_INGRESS_PATH1}#
  secretTls: #{VAR_ENV_HELM_VALUES_INGRESS_SECRET_TLS_NAME}#

autoscaling:
  enabled: #{VAR_ENV_HELM_VALUES_HPA_ENABLED}#
  minReplicas: #{VAR_ENV_HELM_VALUES_HPA_MIN_REPLICAS}#
  maxReplicas: #{VAR_ENV_HELM_VALUES_HPA_MAX_REPLICAS}#
  targetCPUUtilization: #{VAR_ENV_HELM_VALUES_HPA_TARGET_CPU_UTILIZATION}#
  targetMemoryUtilization: #{VAR_ENV_HELM_VALUES_HPA_TARGET_MEMORY_UTILIZATION}#


serviceAccount:
  create: #{VAR_ENV_HELM_VALUES_SA_ENABLED}#
  name: #{VAR_ENV_HELM_VALUES_SA_NAME}#

env:
  SPRING_PROFILES_ACTIVE: #{VAR_ENV_HELM_VALUES_ENVS_SPRING_PROFILES_ACTIVE}#

nodeSelector: {}

tolerations: []

affinity: {}

