apiVersion: v1
kind: Service
metadata:
  name: #{VAR_ENV_K8S_SVC_NAME}#
  namespace: #{VAR_ENV_K8S_NS_NAME}#
  labels:
    app.kubernetes.io/name: #{VAR_ENV_K8S_SVC_NAME}#
    app.kubernetes.io/instance: #{VAR_ENV_K8S_SVC_NAME}#
spec:
  type: #{VAR_ENV_K8S_SVC_TYPE}#
  selector:
    app.kubernetes.io/name: #{VAR_ENV_K8S_DEPLOY_NAME}#
    app.kubernetes.io/instance: #{VAR_ENV_K8S_DEPLOY_NAME}#
  ports:
    - name: http
      port: #{VAR_ENV_K8S_SVC_PORT}#
      targetPort: #{VAR_ENV_K8S_SVC_TARGET_PORT}#
