{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ms-bcodex-spring-techs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ms-bcodex-spring-techs.labels" . | nindent 4 }}
{{- end }}