name: ghw-bcodex-gate-cnt

on:
  pull_request:
    branches:
      - develop
    workflow_dispatch:

env:
  ORG: jhordan01
  APP: ms-bcodex-spring-techs

jobs:
  lint_build_scan:
    runs-on: [self-hosted, runner-dev]
    steps:
      - name: stp-checkout
        uses: actions/checkout@v7

      - name: stp-lintDockerfile
        uses: hadolint/hadolint-action@v3.4.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
      
      - name: stp-setupQEMU
        uses: docker/setup-qemu-action@v4.2.0

      - name: stp-setupBuildx
        uses: docker/setup-buildx-action@v4.2.0
        with:
          version: latest
          buildkitd-flags: --debug
      
      - name: stp-buildImage
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.ORG }}/${{ env.APP }}:pr-${{ github.sha }}

      - name: stp-setupTrivy
        uses: aquasecurity/setup-trivy@v0.3.1
        with:
          cache: true
          version: v0.69.3
      
      - name: stp-vulnerabilityScanTrivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ env.ORG }}/${{ env.APP }}:pr-${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          skip-setup-trivy: true

      - name: stp-generateSBOMTrivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ env.ORG }}/${{ env.APP }}:pr-${{ github.sha }}
          format: cyclonedx
          output: sbom.cdx.json
          exit-code: '0'
          skip-setup-trivy: true
      
      - name: stp-uploadSBOM
        uses: actions/upload-artifact@v7
        with:
          name: sbom-pr-${{ github.sha }}
          path: sbom.cdx.json

      
      - name: stp-installContainerStructureTest
        run: |
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/download/v1.22.1/container-structure-test-linux-arm64
          chmod +x container-structure-test-linux-arm64
          cp -v container-structure-test-linux-arm64 $HOME/bin/container-structure-test
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: stp-runContainerStructureTest
        run: |
          container-structure-test test \
            --image ${{ env.ORG }}/${{ env.APP }}:pr-${{ github.sha }} \
            --config tests/container-structure-test.yaml



          
